### ISSUE TITLE
Oxygen version 16 support?

### ISSUE THREAD

**Issue by nigelmegitt** [oxygenxml/ebu-tt#1]
Hi, not sure if this is the right place to ask this question, but is there anything in this add-on that particularly requires Oxygen 17+? I ask because I still have Oxygen 16 (and it's difficult for me to upgrade because of corporate policies) and would really like to be able to try this out.

**Comment by raducoravu** [comment]
I think the honest answer is that nobody tested it with Oxygen 16. So it might work..., it's best to try this yourself. There are various CSS extension functions that we use in the CSSs used for rendering the XML in the Author and if the CSS in this framework uses an extension which did not exist in Oxygen version 16, there will be a warning open opening the XML in the Author visual editing mode but probably most of the editing functionality will still work.
